"use-client";
import { Providers } from "./providers";
import "@/styles/globals.css";
import theme from "@/styles/theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers theme={theme}>{children}</Providers>
      </body>
    </html>
  );
}
